# Generated by Django 4.0.5 on 2022-07-05 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_profilemodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z]{1}[a-z]{1,19})$', 'Name must start with the capital letter and contain from 2 to 20 letters. Example: Andriy')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+380[\\d]{9}$', 'Invalid phone number. Example: +380xxxxxxxxx')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z]{1}[a-z]{1,19})$', 'Surname must start with the capital letter and contain from 2 to 20 letters. Example: Popov')]),
        ),
    ]
